server:
  bindAddress: "0.0.0.0:4180"

upstreamConfig:
  upstreams:
    - id: static
      path: /
      uri: "static://200"

providers:
  - id: google
    provider: google
    clientID: ${OAUTH2_PROXY_CLIENT_ID}
    clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
    scope: "openid email profile"

injectResponseHeaders:
  - name: X-Auth-Request-Email
    values:
      - claimSource:
          claim: email
  - name: X-Auth-Request-User
    values:
      - claimSource:
          claim: user
  - name: X-Auth-Request-Preferred-Username
    values:
      - claimSource:
          claim: preferred_username
